conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from msilib.schema import AdminExecuteSequence
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.contrib import admin
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:index'), name='logout'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

puddle/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('users/', include('users.urls')), 
    path('checkout/', include('checkout.urls')),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('paypal.standard.ipn.urls')),
    path('transaction/', include('transactions.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# users/urls.py
# users/urls.py
from django.urls import path
from .views import view_profile, update_profile

app_name = 'users'

urlpatterns = [
    path('view_profile/', view_profile, name='view_profile'),  # Make sure to define the name parameter
    path('update_profile/', update_profile, name='update_profile'),
    # other URLs
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
   
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    })) 

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from item.models import Category, Item
from .forms import SignupForm, LoginForm
from django.contrib import messages

def home(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # Verify reCAPTCHA
            captcha_value = request.POST.get('g-recaptcha-response', '')
            if not captcha_value or not form.fields['captcha'].verify(captcha_value, request.META.get('REMOTE_ADDR')):
                messages.error(request, "Error verifying reCAPTCHA, please try again.")
            else:
                # reCAPTCHA verification successful
                messages.success(request, "Success!")
        else:
            messages.error(request, "Form validation error!")
    else:
        form = LoginForm()
    
    return render(request, 'login.html', {'form': form})

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "index.html" 

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Online Marketplace</title>
        <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/4003/4003655.png">
        <style>
            #mobile-menu {
  /* Existing styles... */
  left: 100;
  right: 0;
}
        </style>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">FreshZone</a>
        
            <div class="lg:hidden">
                <button type="button" id="menu-toggle" class="text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700" aria-label="Toggle menu">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
                <div id="mobile-menu" class="hidden absolute z-10 bg-white rounded-xl shadow-md mt-2 py-2 w-48">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'conversation:inbox' %}" class="block px-4 py-2 text-lg font-semibold text-gray-700 hover:bg-gray-100">Inbox</a>
                        <!-- <a href="{% url 'dashboard:index' %}" class="block px-4 py-2 text-lg font-semibold text-gray-700 hover:bg-gray-100">Dashboard</a> -->
                        <a href="{% url 'core:logout' %}" class="block px-4 py-2 text-lg font-semibold text-gray-700 hover:bg-gray-100">Logout</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="block px-4 py-2 text-lg font-semibold text-gray-700 hover:bg-gray-100">Sign up</a>
                        <a href="{% url 'core:login' %}" class="block px-4 py-2 text-lg font-semibold text-gray-700 hover:bg-gray-100">Log in</a>
                    {% endif %}
                </div>
            </div>
        
            <div class="hidden lg:block space-x-6">
                <!-- <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a> -->
               
        
                {% if request.user.is_authenticated %}
                    <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                    <a class="text-lg font-semibold hover:text-gray-500" href="{% url 'transactions:user_purchases' %}">Transactions</a>
                    <a href="{% url 'conversation:inbox' %}" class="text-lg font-semibold hover:text-gray-500">Inbox</a>
                    <a href="{% url 'users:update_profile' %}" class="text-lg font-semibold hover:text-gray-500">Profile</a>
                    <!-- <a href="{% url 'dashboard:index' %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a> -->
                    <a href="{% url 'core:logout' %}" class="text-lg font-semibold bg-gray-500 text-white rounded-xl px-6 py-3 hover:bg-gray-700">Logout</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="text-lg font-semibold bg-teal-500 text-white rounded-xl px-6 py-3 hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="text-lg font-semibold bg-gray-500 text-white rounded-xl px-6 py-3 hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        

        <footer class="py-6 px-6 flex flex-col lg:flex-row justify-between bg-gray-800">
            <div class="w-full lg:w-2/3 pr-10">
                <h3 class="font-semibold text-gray-400">© Copyright 2023 Freshzone All Rights Reserved.</h3>
                <!-- <p class="text-lg text-gray-500" style="text-align: justify;">The Group 1 Project is an innovative online marketplace that provides customers with easy access to a wide range of fresh fruits, vegetables, and meats. The system is designed with CRUD functionality, allowing users to easily create, read, update, and delete products on the platform. Additionally, the platform integrates a Single Sign-On (SSO) API, ensuring that users can easily and securely sign in to the platform using their existing credentials from other platforms. The marketplace is user-friendly and provides customers with a seamless shopping experience, allowing them to browse and purchase products from the comfort of their homes. With its intuitive design and advanced features, the Group 1 Project online marketplace is poised to revolutionize the way people shop for fresh food online.</p> -->

            </div>
        </footer>
    </body>
</html>

<script>
    // JavaScript code to handle the dropdown menu toggle
    const menuToggle = document.getElementById('menu-toggle');
    const mobileMenu = document.getElementById('mobile-menu');

    menuToggle.addEventListener('click', function() {
        mobileMenu.classList.toggle('hidden');
    });
</script>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/home.html
<h1>hola</h1>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> 

        {% if request.user.is_authenticated %}
            <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 justify-center items-center">
                {% for item in items %}
                    <a href="{% url 'item:detail' item.id %}" class="item-link">
                        <div class="item-container bg-white rounded-lg shadow-md overflow-hidden">
                            <div class="item-image">
                                <img src="{{ item.image.url }}" class="w-full h-52 object-cover rounded-t-lg transition-transform duration-300 transform-gpu hover:scale-105">
                            </div>
                            <div class="item-details p-4">
                                <h2 class="text-lg font-semibold">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div> 
     

        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>

            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 justify-center items-center">
                {% for category in categories %}
                    <a href="#" class="category-link">
                        <div class="category-container bg-white rounded-lg shadow-md flex flex-col justify-between">
                            <div class="category-details p-6">
                                <h2 class="text-2xl">{{ category.name }}</h2>
                                <p class="text-gray-500">{{ category.items.count }} items</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}

            </div>
        {% else %}
            <div class="grid grid-cols-1 lg:grid-cols-5 gap-6">
               
                <div class="lg:col-span-3 bg-gray-100 rounded-xl">
                    <div class="p-6">
                        <h1>Welcome to FreshZone</h1>
                        <h2>Hassle-free shopping</h2>
                        <a class="btn" href="#">Get Started</a>
                    </div>
                </div>
                <div class="lg:col-span-2">
                    <img src="https://webstockreview.net/images/clipart-png-vegetable-14.png" class="rounded-xl">
                </div>
        {% endif %}
    </div>


    <style>
        .item-link,
        .category-link {
            text-decoration: none;
        }

        .item-container,
        .category-container {
            height: 100%;
        }
        .btn{
            display: block;
            width: 115px;
            height: 50px;
            background: darkgoldenrod;
            padding: 10px;
            text-align: center;
            border-radius: 10px;
            color: white;
            font-weight: bold;
            line-height: 25px;
        }

        .item-image {
            position: relative;
            overflow: hidden;
            height: 0;
            padding-top: 100%; /* Maintain a square aspect ratio */
        }

        .item-image img {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            transition: transform 0.3s ease-in-out;
        }

        .item-image:hover img {
            transform: scale(1.05);
        }
    </style>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        {% if request.resolver_match.url_name != 'login' %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert text-center mt-5 alert-{{message.tags}}" >
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}

        <form action="" method="post" class="text-center mt-5">
            {% csrf_token%}
            {{form.captcha}}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>


    </form>
    <hr class="my-6 border-gray-300">
    
    <p class="text-gray-500"><strong>or Login with social media account:</strong></p>
    <br>
        <a href="{% url 'social:begin' 'facebook' %}" class="flex items-center justify-center space-x-2 py-2 px-4 bg-blue-700 text-white rounded-md hover:bg-blue-800">
        <svg class="w-5 h-5" viewBox="0 0 24 24">
            <path fill="currentColor" d="M17.4 4H6.6C5.5 4 4.6 4.9 4.6 6v11c0 1.1.9 2 2 2h5.1v-5.9h-1.6v-2.3h1.6V9.8c0-1.6 1-2.5 2.5-2.5h1.9v2.3h-1c-.3 0-.6.3-.6.6v1.4h1.7l-.2 1.7h-1.5v5.9h3.1c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2z"></path>
        </svg>
        <span>Login with Facebook</span>
        </a>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}